### ISSUE TITLE
ORA-06553: PLS-907: cannot load library unit SYS.XQSEQUENCEFROMXMLTYPE

### ISSUE THREAD

**Issue by MarkSorin** [mt-ag/apex-flowsforapex#100]
Question：
ORA-29900: operator binding does not exist
ORA-06540: PL/SQL: compilation error
ORA-06553: PLS-907: cannot load library unit SYS.XQSEQUENCEFROMXMLTYPE (referenced by SYS.XQSEQUENCE)

Location：
package FLOW_BPMN_PARSER_PKG
procedure parse_collaboration line: 818

-- --------------
for rec in (
                 select colab_id
                      , colab_name
                      , colab_type
                      , colab_src_ref
                      , colab_tgt_ref
                   from xmltable
                        (
                          xmlnamespaces ('http://www.omg.org/spec/BPMN/20100524/MODEL' as "bpmn")
                        , '/bpmn:definitions/bpmn:collaboration/*' passing pi_xml
                          columns
                            colab_id      varchar2(50 char)  path '@id'
                          , colab_name    varchar2(200 char) path '@name'
                          , colab_type    varchar2(50 char)  path 'name()'
                          , colab_src_ref varchar2(50 char)  path '@sourceRef'
                          , colab_tgt_ref varchar2(50 char)  path '@targetRef'
                        ) colab
    ) loop
-- -------------------

> select * from v$version
Oracle Database 12c Enterprise Edition Release 12.1.0.2.0 - 64bit Production	0
PL/SQL Release 12.1.0.2.0 - Production	0
CORE	12.1.0.2.0	Production	0
TNS for 64-bit Windows: Version 12.1.0.2.0 - Production	0
NLSRTL Version 12.1.0.2.0 - Production	0

How to fix it?

**Comment by rallen2010** [comment]
Can you send the diagram you were trying to parse? 

Regards, 
Richard 

Richard Allen
+44 (0)7758 155930

**Comment by rallen2010** [comment]
Just noticed that you are running Oracle Database v 12.1.  Our minimum database version is v 12.2.  Looks like you have found the features from 12.2 that we rely on..... Sorry.

**Comment by MarkSorin** [comment]
Thanks for your reply. make me more confident to solve it. 
No matter which parse will be that.
I debugged and found that the problem occurred during xmltable query. 

> 
select colab_id
, colab_name
, colab_type
, colab_src_ref
, colab_tgt_ref
from xmltable
(
xmlnamespaces ('http://www.omg.org/spec/BPMN/20100524/MODEL' as "bpmn")
, '/bpmn:definitions/bpmn:collaboration/*' passing pi_xml
columns
colab_id varchar2(50 char) path '@id'
, colab_name varchar2(200 char) path '@name'
, colab_type varchar2(50 char) path 'name()'
, colab_src_ref varchar2(50 char) path '@sourceRef'
, colab_tgt_ref varchar2(50 char) path '@targetRef'
) colab

Report an error when executed on my server. 
ORA-29900: operator binding does not exist
ORA-06540: PL/SQL: compilation error
ORA-06553: PLS-907: cannot load library unit SYS.XQSEQUENCEFROMXMLTYPE (referenced by SYS.XQSEQUENCE)

On other 11g and 12.2C will be not, maybe a version issue like you said. 
But I want to confirm whether it can be resolved on V12.1, What support may be missing?

**Comment by commi235** [comment]
This looks a bit like the issue mentioned on support.oracle.com in document id 2249619.1.
Can you check that "Oracle XML Database (XDB)" is installed?
