### ISSUE TITLE
performance for timer

### ISSUE THREAD

**Issue by arashEghtedar** [mt-ag/apex-flowsforapex#103]
Good job to all contributors! Keep it up! This is project is incredible.
this is a awesome project .
but one question ...
in work with timer object ,is this better to work with one job and check FLOW TIMERS table every 10 seconds or create one job per timers and check its work on exact time ?

**Comment by rallen2010** [comment]
That's a good question.  It all depends on the workload.  If it's very occasional use, like on our demo systems, it would be better to have them tied to individual timers, but if the system is busy and has lots of timers set, limiting it to once every 10 sec is probably good.  
There are a few things we can do to tune this once we get more feedback from production loads.  
I could see a daily queue for long delays ( sales ticklers) separate from shorter process delays. For lighter used systems, maybe we turn off if Timer queue is empty.

**Comment by arashEghtedar** [comment]
thanks @rallen2010
