### ISSUE TITLE
Timer Event followed by Script- or Service-Task throw Error  in Job

### ISSUE THREAD

**Issue by madmexx2002** [mt-ag/apex-flowsforapex#107]
Hello everybody

When a timer boundary event is followed by a script or service task the scheduler job throw an Error #1002. 
The PL/SQL Code for the script task is just "null;". 
When i switch back to a user task after the timer event all runs right. 
Same error for Interrupting Timer Boundary Event, too.

Greetings Mark

Error Message from the Scheduler Job
```
ORA-01002: FETCH auf ungültigen oder geschlossenen Cursor. 
ORA-06512: in "F4A.FLOW_TIMERS_PKG", Zeile 102
ORA-06512: in "F4A.FLOW_TIMERS_PKG", Zeile 102
```

I used for demonstration Tutorial AA7
![image](https://user-images.githubusercontent.com/36326420/103565847-56fce100-4ec1-11eb-84b4-494bccbd7011.png)

**Comment by rallen2010** [comment]
Hi Mark

Thanks.  I’m aware of this bug.  Will try to get fixed later this month.  I think we introduced this in 5.0.1 when we fixed a related bug.

**Comment by madmexx2002** [comment]
Hi Richard

If i understood the code, one of the errors is the call to apex_exec.execute_plsql without a apex session. in FLOW_PLSQL_RUNNER_PKG. Quick and very dirty solution, create a session to dummy application. This let the service task execute the pl/sql. But the ORA-01002 is still there and the flow wont move to the next step after executing the pl/sql block.

In my oppinion, for timers avoid apex_exec.execute_plsql.

Mark
