### ISSUE TITLE
Download the BPMN definition in a file instead of showing it in a modal dialog.

### ISSUE THREAD

**Issue by nielsdebr** [mt-ag/apex-flowsforapex#125]
Instead of showing the XML definition in a modal dialog, the "download" button should immediately start a file download. The filename used is <yyyy-mon-dd_hh24-mi_diagramname.bpmn>

**Comment by commi235** [comment]
Only saved diagrams can be downloaded using this functionality.
Include on "Diagram Management" page as an additional button per diagram.

File Naming:
Do we need/want to include category, version, change_date etc.?
Maybe allow user to configure the download?

File Formats:
Do we want to provide multiple download formats?
XML vs. Import Script (SQL)
