### ISSUE TITLE
Add a check in the modeler that warns if the ID of an object is left unchanged.

### ISSUE THREAD

**Issue by nielsdebr** [mt-ag/apex-flowsforapex#126]
After clicking on an object, the property ID is set to something like "Gateway_dFfs23d". This value is be unique, but very cryptic by default. Best practise would be to rename it to something more readable like "Gateway_isAdult".

A new BPMN linter check is to be introduced which checks if the default ID is still present. If so, a warning like "It is best practise to rename the default ID to something more understandable." is given.

**Comment by nielsdebr** [comment]
This issue will be solved by the modeler project, so it can be closed here.

**Comment by rallen2010** [comment]
would this be just for objects, or also for connections (sequenceFlow, messageFlow) as well?

**Comment by StephanRamke** [comment]
My current plan is to implement this for all objects. If it makes sense, it can be restricted to certain object types.
