### ISSUE TITLE
Login as standard user not as an Admin with SSO

### ISSUE THREAD

**Issue by dobija** [mt-ag/apex-flowsforapex#127]
![image](https://user-images.githubusercontent.com/49499055/106788206-f47a3a80-6650-11eb-834c-a7fb47cb20d2.png)

**Comment by rallen2010** [comment]
can you provide a bit more information about what you were doing, please - ideally including some debug files.

**Comment by dobija** [comment]
We have sso used and we want to give the app for writing process to our users but when I change to sso it displays that message

Apex 20.1

**Comment by dobija** [comment]
![image](https://user-images.githubusercontent.com/49499055/106789110-1cb66900-6652-11eb-8d03-ad0830ac52b8.png)

**Comment by nielsdebr** [comment]
Could you please reproduce this issue on apex.oracle.com and give us development access to your workspace? Thanks.

**Comment by dobija** [comment]
no we have kerberos here and on .com there is no such installlation so will not mirror it

**Comment by dobija** [comment]
what is more important it works with apex users and no authorization

**Comment by nielsdebr** [comment]
I suggest you book a support session through https://apex.mt-ag.com/ords/f?p=APEXSUPPORT:3:0&p_lang=en so that we can look over your environment using Zoom.

**Comment by dobija** [comment]
its not free of charge and I understand it since time costs but we are just trying if use it

**Comment by dobija** [comment]
we can not use Post-Authentication Procedure Name in your application
