### ISSUE TITLE
apex page with user task

### ISSUE THREAD

**Issue by arashEghtedar** [mt-ag/apex-flowsforapex#133]
hi every body. when we set a page and request type to an user Task, how that page Pushing forward the step of process, when we are in that page (should we call any functionality in that page ?)

**Comment by rallen2010** [comment]
When you call the user task, you should pass in its context (process_id, subflow_id).  When the task is complete, it then needs to call flow_api_pkg.flow_task_complete( process_id, subflow_id); to move the process model forwards.

**Comment by arashEghtedar** [comment]
tanks @rallen2010, but we can not find  this function or procedure in that package, is there any conflict ?

**Comment by rallen2010** [comment]
sorry - comment above corrected.  flow_api_pkg.flow_complete_step( process_id, subflow_id);

**Comment by arashEghtedar** [comment]
thanks @rallen2010
