### ISSUE TITLE
Timer Duration strings using Months & Years fail

### ISSUE THREAD

**Issue by rallen2010** [mt-ag/apex-flowsforapex#154]
Timer Duration string accepts an ISO 8601 Duration string - like 'PT50S' or 'PT2M' - and behaves as expected.  If the duration includes a non-time component, for example 3 months or 1 year+2months, 'P3M' or 'P1Y2M', it fails.

Test harness for flow_timers_pkg.get_duration is

`set serveroutput on;
declare
    l_interv_ym varchar2(20);
    l_interv_ds varchar2(20);
    l_start_ts timestamp with time zone;
begin
    flow_timers_pkg.get_duration
        ( in_string => 'P3M'
        , in_start_ts => systimestamp
        , out_start_ts => l_start_ts
        , out_interv_ym => l_interv_ym
        , out_interv_ds => l_interv_ds
        );
        
    dbms_output.put_line('systimestamp'|| systimestamp);
    dbms_output.put_line('l_start_ts:'|| l_start_ts);
    dbms_output.put_line('l_interv_ym:'|| l_interv_ym);
    dbms_output.put_line('l_interv_ds'|| l_interv_ds);
end;
        `
This works for PT3M (3 minutes) but fails for 'P3M' or 'P1Y2M'.
Also - there's no error handling in get_duration -- so any invalid string fails without a nice error message, which is not good!  User ends up with a 'JSON not complete/ EOF' type error, which is not good for non-trivial user config parameter.

**Comment by commi235** [comment]
fixed in v5.1.0
