### ISSUE TITLE
Export Page - Unexpected internal application error

### ISSUE THREAD

**Issue by madmexx2002** [mt-ag/apex-flowsforapex#160]
Hi

I opened Diagram AA8 and then hit "Export" Button. On the Export Page i selected every switch. Internal error is thrown when i switched the 4th to on. The order does not matter. 

Regards Mark

**Comment by commi235** [comment]
Just tried on my local Virtual Machine.
Instant download for that one.
Could you include a screenshot and other details?

**Comment by madmexx2002** [comment]
Hi Moritz

I have played with your FFA on apex.oracle.com.  

![image](https://user-images.githubusercontent.com/36326420/109523983-41b2c600-7ab0-11eb-832e-6370272e0ae7.png)

**Comment by commi235** [comment]
Thanks for the information.
I have applied a quick fix for this on apex.oracle.com.
Interestingly we did not reserve enough characters for the output file name.

**Comment by madmexx2002** [comment]
Now, it is running. 
Thx for the quick fix and thx for the great work for FFA.
I like it very much :)

**Comment by commi235** [comment]
Thanks for feedback, I'll close down this one as I have opened a specific bug ticket for this issue.
Permanent bugfix incoming for next minor release.
