### ISSUE TITLE
flow_p0005_api filename return too small

### ISSUE THREAD

**Issue by commi235** [mt-ag/apex-flowsforapex#161]
This is related to #160.
Steps needed to fix:
- reserve more characters for filename
- introduce error handling and possibly truncation of generated filename

**Comment by commi235** [comment]
In addition we should also have a look at reducing the filename length.
Probably changing the format masks for date/timestamp data.
Proposed format: `YYYYMMDDHH24MI` (no - or _)
That way the underscore is only used to separate the different parts of the filename.
Should be easier to identify the different parts.

**Comment by madmexx2002** [comment]
Seperate date and time with underscore, too. => Should be easier to identify the different parts...

**Comment by commi235** [comment]
OK, there I'm opting for a dash (-).
${download date-time}_${diagram name}... is what I'm after here

**Comment by madmexx2002** [comment]
For me it is readable with focus on date and dgrm name.
