### ISSUE TITLE
Process ended but left in state running

### ISSUE THREAD

**Issue by commi235** [mt-ag/apex-flowsforapex#165]
A process having just a non-waiting task (e.g. serviceTask) is left in state running, but process diagram shows all steps completed.
Sounds similar to the issue we had with parallel flows, but this time on process level instead of subflow.

Diagram for testing ist attached.
[test_bpmn.txt](https://github.com/mt-ag/apex-flowsforapex/files/6100575/test_bpmn.txt)

**Comment by rallen2010** [comment]
I saw this earlier during 5.1 dev & thought I'd fixed it.  I'll investigate...

**Comment by commi235** [comment]
Check the placement of the update statement for marking the process as running.
Reporter mentioned he moved it to the very top and afterwards everything worked as expected.
If anything goes wrong when starting the process we'll do a rollback so no harm in marking the process immediately as running.
