### ISSUE TITLE
Add support for French (France)

### ISSUE THREAD

**Issue by nielsdebr** [mt-ag/apex-flowsforapex#169]
Components requiring i18n:

- [x] Error message framework in Engine
- [x] bpmn.io UI & integration of bpmn.io i18n features https://github.com/bpmn-io/bpmn-js-i18n
- [x] engine-app support
- [ ] doc

Languages required: (APEX core languages)
- German
- French 
- Italian 
- Spanish
- Japanese 
- Korean
- Simplified Chinese
- Traditional Chinese
- Brazilian Portuguese 

bpmn.io translation files are available for (on GitHub):
Chinese
French
German
Italian
Portuguese
Russian

**Comment by LouisMoreaux** [comment]
Added in 21.1, we don't translate the doc so all done for French
