### ISSUE TITLE
Expose export as image from bpmn-modeler and bpmn-viewer

### ISSUE THREAD

**Issue by commi235** [mt-ag/apex-flowsforapex#170]
Might be a nice enhancement for user to quickly export and distribute diagrams as read only copies (bpmn.js supports SVG by default).

**Comment by nielsdebr** [comment]
If it is possible with a standard routine to create an image out of a BPMN specification, then I would welcome this.

**Comment by nielsdebr** [comment]
Correct, seems to work without much cosing effort from our side. Here is the library that Richard mentioned: https://github.com/bpmn-io/bpmn-to-image.

**Comment by commi235** [comment]
The base library already exposes a method called saveSVG.
I'd opt for starting with that before adding additional dependencies.

**Comment by LouisMoreaux** [comment]
Delivered in version 21.1
