### ISSUE TITLE
Regression Testing for BPMN Engine 

### ISSUE THREAD

**Issue by rallen2010** [mt-ag/apex-flowsforapex#174]
Need to add some form of regression testing for the flow engine and parser to ensure changes don't break other behaviour.

**Comment by nielsdebr** [comment]
Besides testing using PL/SQL, we could also use LCT for UA testing of BPMN models through the app.

**Comment by nielsdebr** [comment]
Using utplsql, we will test various flow diagrams to see if the engine works correctly.

**Comment by rallen2010** [comment]
Initial Suites for v22.2:

- [x] 001 - Basic API
- [x] 002 - Basic Gateway Operation
- [x] 003 - Start Events
- [x] 004 - Process Variables basic operation
- [ ] 005 - parser
- [ ] 009 - callActivity Nesting
- [x] 010 - variable expressions
- [x] 011 - variable expressions in callActivities
- [x] 012 - callActivity timer events
- [x] 013 - callActivity escalation events
- [x] 014 - callActivity error events
- [x] 015 - lanes (inc in callActivities)
- [x] 016 - splitting gateway errors and restarts
- [x] 017 - exclusive gateway errors and restarts
- [x] 018 - gateway routing expressions

**Comment by rallen2010** [comment]
OK - We can always write more (and must and will...) but I'm going to declare this finished for 22.2.  We have written 14 suites, 168 tests, which make ??500?? checks as they progress.   A great start to regression for Flows for APEX!
