### ISSUE TITLE
Review Changing License

### ISSUE THREAD

**Issue by commi235** [mt-ag/apex-flowsforapex#18]
Current GPL V3 is not permitting commercial use without disclosing own source code.
Probably a more permissive one like MIT is more appropriate.

**Comment by nielsdebr** [comment]
I agree on changing to MIT. If all agree on this as well by leaving a comment for this issue, we can switch to MIT without having to revert some changes.

**Comment by nielsdebr** [comment]
BTW: bpmn.io is also MIT together with the requirement of leaving a watermark on the page.

**Comment by rallen2010** [comment]
Ok with me.

**Comment by commi235** [comment]
License changed.
