### ISSUE TITLE
Timers should not rely on the opened cursor for processing

### ISSUE THREAD

**Issue by commi235** [mt-ag/apex-flowsforapex#187]
Currently we are using a cursor loop to process timers.
This can lead to issues when the cursor loop gets invalidated due to processing being handed over to flow_engine.
Rework timers to first get list of timers as a snapshot and then start processing.
Checking for each record if still eligible to run.

**Comment by nielsdebr** [comment]
Did some tests with timers. When it comes to the scope of this issue, it seems to work as expected. Well done.
