### ISSUE TITLE
The general error message when trying to parse is misleading.

### ISSUE THREAD

**Issue by nielsdebr** [mt-ag/apex-flowsforapex#193]
<img width="1047" alt="Screen Shot 2021-03-18 at 09 20 32" src="https://user-images.githubusercontent.com/17747219/111594488-6951a000-87cb-11eb-933b-692eb5e9f9c0.png">

Whenever somebody does something that is not supported (like not specifying a timer duration), I would expect a message like "As we don't support your model definition, we were unable to parse your diagram. Please consult the documentation."

**Comment by commi235** [comment]
In this case the root cause is violation of constraint OBAT_CK.
Meaning the parser tried to insert a new record into object_attributes but all value fields are null.
Will research better options to make parser more robust.

**Comment by commi235** [comment]
In addition need to find a good way to distinguish between error while pushing XML to flow_diagrams table vs. error during parsing.
From what I've seen the diagram is still saved, but parsing fails.
