### ISSUE TITLE
Flow Designer and Flow Monitor plugin zoom-in / zoom-out problems on Windows

### ISSUE THREAD

**Issue by rallen2010** [mt-ag/apex-flowsforapex#195]
Customer reports that the modeller and the monitor plug-ins won't zoom in/out on some browsers.

On Mac, Chrome allow you to zoom in & out to huge levels using pinch & stretch on the trackpad.
On Mac, Safari allows zoom in & out to good (but less than Chrome) levels using command + and command -

On Windows, Chrome and Firefox are reported to not enlarge and shrink to a useful amount.

Please can we test and try to fix for windows for 22.x. in case there are different mechanisms on different browsers that we can use.
(I have to say this, as a Mac user:  Workaround - just get a Mac!) (which was the reporting customer did!!!)

**Comment by commi235** [comment]
Modeler should have navigation inbuilt.
Probably only reacts to zoom gesture.

For the viewer we on purpose disabled the navigation module as it was no good user experience.

In general this needs to be solved in the base libraries.

**Comment by nielsdebr** [comment]
We are adding zooming in 21.1. As there is another ticket for that, I will close this one.
