### ISSUE TITLE
Demo Application on apex.oracle.com - 1 error has occurred

### ISSUE THREAD

**Issue by madmexx2002** [mt-ag/apex-flowsforapex#213]
Hello

The Demo Application - Order Shipment on https://apex.oracle.com/pls/apex/mt_flows/r/flowsforapexdemo/ dosen't work. 
A new Order can not be created. 
Error Message: Cannot find released diagram or draft version 0 of diagram - please specify a version or diagram_id

Greetins Mark

**Comment by nielsdebr** [comment]
Thanks for mentioning this. Seems that the flow got deleted somehow. It now works.

**Comment by madmexx2002** [comment]
Thx
