### ISSUE TITLE
Create a new demo app "Expense Claims".

### ISSUE THREAD

**Issue by nielsdebr** [mt-ag/apex-flowsforapex#222]
We need to ship a demo app for showing off all features of Flows for APEX 21.1. One that is not task-driven (like the Order Shipment Demo), but more feels like an ordinary APEX app.

**Comment by madmexx2002** [comment]
Hi Niels

What about a litte Incident Manager? Under examples there is the IncidentManagement Flow. Instead of triggering that flow from a mail it could be triggert from a feedback / issue dialog and then the magic is flowing.  Maybe i need a better explaination for "not task-driven"

**Comment by nielsdebr** [comment]
Thanks for pointing this out. Based on the tutorial, I will do a slightly adapted version of the expense reimbursement flow.

By "not task-driven" you don't have a central page with all tasks on it. It behaves just like a regular app with Flows for APEX running in the background.

**Comment by LouisMoreaux** [comment]
Delivered in version 21.1
