### ISSUE TITLE
Cycle Timer supporte

### ISSUE THREAD

**Issue by arashEghtedar** [mt-ag/apex-flowsforapex#226]
hello every body
Is Cycle Timers are not currently supported in Flows for APEX Yet ?

**Comment by nielsdebr** [comment]
I'm sure that Richard will give you more details on the reason why, but no, it isn't supported and we plan to take that option out for the upcoming release.

Can you give us some background info about your use case and why you need it?

**Comment by arashEghtedar** [comment]
We need it for some scheduling tasks like Christmas greetings or reminders

**Comment by nielsdebr** [comment]
In this case, perhaps you can trigger off the flow by using an automation in APEX 20.2+?

**Comment by arashEghtedar** [comment]
i try it and I'll announce you

**Comment by arashEghtedar** [comment]
i checked the pakage 
[https://github.com/mt-ag/apex-flowsforapex/blob/e5c63b22d2653b450362909590f47324cc085d8d/src/plsql/flow_timers_pkg.pkb#L327]( https://github.com/mt-ag/apex-flowsforapex/blob/e5c63b22d2653b450362909590f47324cc085d8d/src/plsql/flow_timers_pkg.pkb#L327
)
it has gc_timer_type_cycle !! 
thanks god

**Comment by nielsdebr** [comment]
Have a look at issue 184. We did some work in that area, but there are scenarios where it doesn't make sense to let a timer cycle, hence we don't support it today. That said, you are welcome to experiment and give us your feedback.

**Comment by arashEghtedar** [comment]
> Have a look at issue 184. We did some work in that area, but there are scenarios where it doesn't make sense to let a timer cycle, hence we don't support it today. That said, you are welcome to experiment and give us your feedback.

sure ,It is my pleasure

**Comment by rallen2010** [comment]
Closed - Added to Issue #248 for future release
