### ISSUE TITLE
Several enhancements for the BPMN modeler

### ISSUE THREAD

**Issue by damthor** [mt-ag/apex-flowsforapex#230]
Enhance the modelling tool with multiple features:

- Enable key-bindings for undoing/redoing modelling steps and deleting objects
  _(a help window with a list of possible shortcuts should be added in the engine-app later)_
- Extend the tool palette with buttons for undoing/redoing steps and zooming

A demo of these functions can already be seen in action on bpmn.io and the camunda bpmn modeler.

**Comment by damthor** [comment]
Added in https://github.com/mt-ag/apex-flowsforapex/commit/c9e1778bcccddb724e136f1c9e37d18595a05007 as well as keybindings and zooming functionality via buttons.

**Comment by LouisMoreaux** [comment]
Delivered in version 21.1
