### ISSUE TITLE
Add flow_terminate to API

### ISSUE THREAD

**Issue by rallen2010** [mt-ag/apex-flowsforapex#231]
We've come across 2 users who want to be able to terminate running processes under various external situations (i.e., not using a Terminate End inside the model).  
The only current option from the API is to do a flow_delete -- which is a hard process stop followed by deleting the process and its subflows from the database.  In contrast, a Terminate End Event from inside the model at the parent Subflow level will do a hard process stop in the instance, but leave the process record and its progress (in the subflow_log) intact.
The user requirement in both of these cases is to do, essentially, a Terminating End Event driven from the API.
I propose that we extend the flow_api to create a flow_terminate(p_process_id) call which acts like a terminate end event.

The first customer requirement (via Louis) was to be able to terminate processes that were older than a given date, but leave the processes in place so that you can see what progress had been made before it was terminated.

Second customer requirement (via Richard) was for HR system, where multiple Flows are designed for doing various processes to a person.  If the subject employee quits / new hire doesn't join, you want to terminate any processes that are being performed for him as a subject -- but again, want to know what was actually performed. before it terminated.

This is relatively easy enhancement in the engine & appears to have high benefit in production manageability.

**Comment by nielsdebr** [comment]
Go for it. :)

**Comment by rallen2010** [comment]
Notes to self for later:  flow_engine_util.flow_terminate level - change args from sbfl_id to sbfl_level.  Change calls in flow_engine.  Then create call in flow_instances as flow_terminate.

**Comment by rallen2010** [comment]
Question to Group:  What should be the status of a terminated flow instance?  At present, if it is terminated from inside the model (i.e., a Terminate End Event is processed), it has a status of 'completed', just like any other instance that completes its processing.  To have parallel behaviour when terminated from the API, I have also given the instance a status of 'completed' when it is terminated from the API.
Happy to listen to opinions here....

**Comment by madmexx2002** [comment]
Hi Richard

When a process gets terminated by user (API) is there any information that the process was terminated? If not, a status of terminated would be my choice. Thinking about statistics, say you want to know how long a process is average running from the start to the regular end. To do this, it is necessary to know which processes are to be calculated - Only with status of completed.

**Comment by rallen2010** [comment]
- [ ] Need to parse out the terminated/completed attribute from the Terminate End Event. - Moritz
- [ ] Need to implement switch of status in engine - Richard

**Comment by LouisMoreaux** [comment]
Delivered in version 21.1
