### ISSUE TITLE
Provide api function to get business reference

### ISSUE THREAD

**Issue by damthor** [mt-ag/apex-flowsforapex#235]
When using the plugin option to set the business reference on process creation, the stored business reference can be retrieved using:

`flow_process_vars.get_var_vc2( pi_prcs_id  => p_prcs_id, pi_var_name => 'BUSINESS_REF' )`.

So a user has to know the name and type of the automatically created business reference.

By adding an interface function `get_business_ref( pi_prcs_id  => p_prcs_id)` this could be removed and improve the usage of the business reference inside custom processing packages.

In addition, the name of the business reference variable should be stored inside the flow_constants package to ensure consistent usage throughout the packages.

**Comment by rallen2010** [comment]
Ok - done.  Setting the variable still uses standard process variable set_var()...

**Comment by rallen2010** [comment]
Should get_business_ref return `null` if it is not set?  That would-be better than an error, right?

**Comment by LouisMoreaux** [comment]
Delivered in version 21.1
