### ISSUE TITLE
Support for dark mode in the Flows for APEX app.

### ISSUE THREAD

**Issue by nielsdebr** [mt-ag/apex-flowsforapex#263]
We need to first analyze the needed customizations in bpmn.io to get this supported. Low priority.

**Comment by damthor** [comment]
In bpmn.js the color theming is realized by css variables. We can override those and pick the correct variable value depending on the selected theme. I prepare the needed coloring changes to modeler and viewer so we can test it.

**Comment by LouisMoreaux** [comment]
Included in version 21.1
