### ISSUE TITLE
Modal titles (Audit pages)

### ISSUE THREAD

**Issue by LouisMoreaux** [mt-ag/apex-flowsforapex#286]
The way the modal dialog titles are currently set overwrites all the modal dialog titles. This is not a problem when opening a new page, but for inline dialogs, they inherit their titles from the previous open audit dialog.

![image](https://user-images.githubusercontent.com/42840524/132318105-268dc9ae-272c-4be1-bb09-864ab05fa3b5.png)
![image](https://user-images.githubusercontent.com/42840524/132318184-97752a95-3d64-436e-bb25-ffa290f82837.png)

**Comment by damthor** [comment]
Closed in https://github.com/mt-ag/apex-flowsforapex/commit/57b174edf150b2f5b4fa2d65925b17e23adb0f99
