### ISSUE TITLE
SVG Export (21.1 beta)

### ISSUE THREAD

**Issue by madmexx2002** [mt-ag/apex-flowsforapex#288]
The exported SVG is without color. Every Object and fonts are in black color with dark overlay. Opened the SVG in Chrome, Edge and Gimp. I putted the SVG into the attached zip.

[Full Syntax (Version_ 0, Status_ draft).zip](https://github.com/mt-ag/apex-flowsforapex/files/7123356/Full.Syntax.Version_.0.Status_.draft.zip)

**Comment by damthor** [comment]
I assume this only occurs when exporting from the modeler, the viewer export should be fine.
This is due to a missing fix to adjust the color independent of the chosen theme mode. We will add that to the modeler too.

**Comment by madmexx2002** [comment]
Hi Dennis. I checked this again, You're right, the mistake is only in the modeler.

**Comment by damthor** [comment]
Closed in https://github.com/mt-ag/apex-flowsforapex/commit/8d7db616805052fa96397da12a93aefdfc1bbd95
