### ISSUE TITLE
TIMESTAMP columns do not hold the current time zone

### ISSUE THREAD

**Issue by rod-west** [mt-ag/apex-flowsforapex#300]
There is a issue with the TIMESTAMP(6) WITH TIME ZONE data type and the OCI autonomous database. The OCI database has the DBTIMEZONE set to GMT and SESSIONTIMEZONE set to EUROPE/LONDON. The timestamp columns are updated using SYSTIMESTAMP and therefore the time is stored with the GMT time zone. Consequently, all times showing in the application are shown as GMT and so are an hour behind.

I think there are 3 options to resolve this:
1. Use the TIMESTAMP WITH LOCAL TIME ZONE as the column data type. Then the time zone is not stored in the column and the time is always displayed using the current time zone.
2. Use CURRENT_TIMESTAMP to update the columns. Then the times are stored with the current time zone. The time will be displayed using the time zone that was used when the table was updated.
3. The views or queries that display times convert the timestamp to the current time zone using "at time zone SESSIONTIMEZONE". The times will then always be displayed using the current time zone.

I would go with option 2.

**Comment by commi235** [comment]
Another option:
Always use database timezone on all entries, therefore using systimestamp.
The Engine-App should then make sure to enable automatic timezone as needed.

This will make sure that if you look at entries in the database you have it rather easy as all entries use the same (database) timezone.
Not connected to which client timezone was used, but can always be converted into respective client timezone.

In general I prefer not to mix different timezones when storing the data.
Timezone conversion should be done when reading the data.

**Comment by rod-west** [comment]
The option you choose depends on what the users need to see. If the users need to see the local time when the record was updated then the time zone needs to be held in the column, so you have to use TIMESTAMP WITH TIME ZONE as the column type. This gives the most functionality as if the user saved the record at 10am PST the viewer can see the record was updated at 10am PST and can convert the time to current time zone, eg. 6pm BST. 
If the user doesn't need to see when the time zone when the record was updated then TIMESTAMP WITH LOCAL TIME ZONE data type is the best option. Then all times are converted to the DBTIMEZONE and the time zone is not stored in the column. Unlike the TIMESTAMP data type, it doesn't matter if you update the record with systimestamp or current_timestamp, the time stored is the same. When viewing the column the default is to view the time using the SESSIONTIMEZONE.

**Comment by commi235** [comment]
I just checked all TIMESTAMP columns in the data model.
They all are with TIMEZONE, so timezone should be captured and therefore any conversion can be done when reading the data.
Probably some misunderstanding from my side.

**Comment by LouisMoreaux** [comment]
We have chosen to keep TIMESTAMP WITH TIME ZONE and modify the engine application views to display the datas in the user's time zone.
