### ISSUE TITLE
unsupported startEvent subtypes are started

### ISSUE THREAD

**Issue by rallen2010** [mt-ag/apex-flowsforapex#305]
We currently only support None startEvents (standard start) and Timer startEvents.
As we only look for timer subtypes, all other timer types (e., message Startevents) get parsed as none StartEvents & we then  start them as if they were none startEvents (without waiting for a message event, etc.,).
Correct behaviour should be that we raise an error when models contain these unsupported startevents.

**Comment by damthor** [comment]
Linter rule added in 5863e5d5e5576186dde7430a4b0b48dcb7cca965, the modeler now warns when using unsupported start event types.
