### ISSUE TITLE
Parse subTags and other attributes below steps

### ISSUE THREAD

**Issue by commi235** [mt-ag/apex-flowsforapex#32]
Currently the parser stops at "step" level.
Some elements have additional information below that level.
E.g. Terminating End Event can only be derived from looking below endEvent.
In addition timer details ar available at that level.

Adapt parser to also parse out those parts.
Put known elements onto sub_tag_name if needed.
Everything else goes to the new flow_object_attributes table.

**Comment by rallen2010** [comment]
required for existing features - Terminate End Events, Timer Start Events, Timer Intermediate Events.
required for almost everything else we will add!
Important for 5.0 (or even a 4.1 if we do one).
