### ISSUE TITLE
Create model button throwing error

### ISSUE THREAD

**Issue by gdgideonpersonal** [mt-ag/apex-flowsforapex#342]
After installing the flows application in my Apex model 20, whenever i click on the create model button this error comes up.

Technical Info (only visible for developers)
is_internal_error: true
apex_error_code: WWV_FLOW_FORMS.ITEM_DEFAULT_ERR
original message: Error computing item default value for page item Initialize form Edit Diagram.
original_additional_info: Contact your application administrator.
ora_sqlcode: -6550
ora_sqlerrm: ORA-06550: line 1, column 43: PLS-00905: object XXHR.FLOW_CONSTANTS_PKG is invalid ORA-06550: line 1, column 7: PL/SQL: Statement ignored
component.type: APEX_APPLICATION_PAGE_PROCESS
component.id: 538193687913197689
component.name: Initialize form Edit Diagram
error_backtrace:
ORA-06512: at "SYS.DBMS_SYS_SQL", line 1445
ORA-06512: at "SYS.WWV_DBMS_SQL_APEX_200200", line 544
ORA-06512: at "APEX_200200.WWV_FLOW_CODE_EXEC_PLSQL", line 144
ORA-06512: at "APEX_200200.WWV_FLOW_CODE_EXEC", line 63
ORA-06512: at "APEX_200200.WWV_FLOW_FORMS", line 1311
error_statement:
begin wwv_flow.g_computation_result_vc := flow_constants_pkg.gc_dgrm_status_draft;
end;

**Comment by LouisMoreaux** [comment]
Hello,
It seems that the package flow_constants_pkg is invalid, can you compile the package and see what is the issue?
Additionnal question, how do you install the application? With the packaged app in the APEX builder? If yes, maybe take a look at the Install Summary to get more details.

**Comment by gdgideonpersonal** [comment]
Yes the flow_constants_pkg is invalid and this is the error 

[Error] PLS-00114 (17: 3): PLS-00114: identifier 'GC_BPMN_INTERMEDIATE_THROW_EVE' too long
[Error] PLS-00114 (18: 3): PLS-00114: identifier 'GC_BPMN_INTERMEDIATE_CATCH_EVE' too long
[Error] PLS-00114 (20: 3): PLS-00114: identifier 'GC_BPMN_TERMINATE_EVENT_DEFINI' too long
[Error] PLS-00114 (22: 3): PLS-00114: identifier 'GC_BPMN_ESCALATION_EVENT_DEFIN' too long
[Error] PLS-00114 (24: 3): PLS-00114: identifier 'GC_BPMN_MESSAGE_EVENT_DEFINITI' too long
[Error] PLS-00114 (25: 3): PLS-00114: identifier 'GC_BPMN_CONDITIONAL_EVENT_DEFI' too long
[Error] PLS-00114 (26: 3): PLS-00114: identifier 'GC_BPMN_SIGNAL_EVENT_DEFINITIO' too long
[Error] PLS-00114 (64: 3): PLS-00114: identifier 'GC_SUBSTITUTION_FLOW_IDENTIFIE' too long
[Error] PLS-00114 (114: 3): PLS-00114: identifier 'GC_EXPR_TYPE_SQL_DELIMITED_LIS' too long
[Error] PLS-00114 (115: 3): PLS-00114: identifier 'GC_EXPR_TYPE_PLSQL_FUNCTION_BO' too long
[Error] PLS-00114 (130: 3): PLS-00114: identifier 'GC_CONFIG_LOGGING_LEVEL_STANDA' too long
[Error] PLS-00114 (136: 3): PLS-00114: identifier 'GC_CONFIG_DEFAULT_LOGGING_LEVE' too long
[Error] PLS-00114 (136: 79): PLS-00114: identifier 'GC_CONFIG_LOGGING_LEVEL_STANDA' too long
[Error] PLS-00114 (137: 3): PLS-00114: identifier 'GC_CONFIG_DEFAULT_LOGGING_HIDE' too long
[Error] PLS-00114 (138: 3): PLS-00114: identifier 'GC_CONFIG_DEFAULT_LOGGING_LANG' too long
[Error] PLS-00114 (139: 3): PLS-00114: identifier 'GC_CONFIG_DEFAULT_ENGINE_APP_M' too long

**Comment by commi235** [comment]
Please give us the Oracle Database Version you're using.
We use identifiers with up to 128 byte length, therefore a minimum database release of 12.2 is required.

**Comment by gdgideonpersonal** [comment]
12.1.0.2

**Comment by LouisMoreaux** [comment]
We are sorry but we only support Oracle database 12.2 and higher (see the [FAQ](https://mt-ag.github.io/apex-flowsforapex/FAQ.html#what-versions-of-oracle-and-oracle-apex-do-you-support) for minimal requirements).

**Comment by gdgideonpersonal** [comment]
Are there earlier versions of the flows i can get to run on the 12.1.0.2?

**Comment by LouisMoreaux** [comment]
Sadly not, sorry.
