### ISSUE TITLE
[bug]: unexpected internal error on startup

### ISSUE THREAD

**Issue by dschleis** [mt-ag/apex-flowsforapex#375]
### Flows for APEX version

21.1

### Oracle Database version

19

### Oracle APEX version

20.1

### What happened?

I installed Flows for APEX on Friday.
I changed the authorization scheme to use internal Windows Azure scheme in use in other apps.
Used Flows.
Saved diagram.
Weekend happened.
Opened Flows4APEX in builder. 
Clicked on "Run application"
![Screen Shot 2021-11-29 at 7 47 31 AM](https://user-images.githubusercontent.com/15113432/143879461-302a927b-1eba-45f7-b3ce-909893cb5d1c.png)
"

### Steps to reproduce

see "What happened"

### Expected behaviour

Expected application to start

**Comment by LouisMoreaux** [comment]
The issue is caused by the change of the authentication scheme on the engine app. Switching back to Application Express Authentication fix the issue. I need to dig further with David to understand what is going on.

**Comment by dschleis** [comment]
The custom authentication scheme contained a post-authentication procedure that was causing the error. All is working now.
