### ISSUE TITLE
[bug]: flow_p0005_api compile error during installation

### ISSUE THREAD

**Issue by ConnyKl** [mt-ag/apex-flowsforapex#377]
### Flows for APEX version

21.1

### Oracle Database version

12.2

### Oracle APEX version

20.2

### What happened?

todays download and installation of Flow for Apex 21.1
end with error in flow_p0005_api package body:

Error at line 213: PL/SQL: Statement ignored
Error at line 213: PLS-00222: no function with name 'R_FLOW' exists in this scope

So - the download of flows doesnt work.

### Expected behaviour

correct code in procedure download_file(..)

**Comment by LouisMoreaux** [comment]
Hello,
We are able to duplicate this issue and are working on the hotfix.

**Comment by LouisMoreaux** [comment]
Fixed in #378 
Hotfix issue-377.sql available for release [21.1](https://github.com/mt-ag/apex-flowsforapex/releases/tag/v21.1)
Thank you for reporting this bug and sorry for the inconvenience
