### ISSUE TITLE
MouseOver Completed Activity in ProcessViewer shows Activity History

### ISSUE THREAD

**Issue by rallen2010** [mt-ag/apex-flowsforapex#41]
Would be nice to be able to mouseover a completed object on the process viewer, bringing up history of who, when, etc., the activity was completed.

This would probably require some work on the logging and audit task to be completed first.

**Comment by commi235** [comment]
I have just implemented a new feature in the plugin.
This exposes various events from the Events of BPMN.io.
Anyone could then react to the events and built custom mouse overs based on those events.

I'll see to push a preview to the Git Repository.

**Comment by commi235** [comment]
Next step is to create an example usage in the Monitoring App.

**Comment by LouisMoreaux** [comment]
Delivered in version 21.1
