### ISSUE TITLE
Joins between flow_subflows and flow_objects need two columns

### ISSUE THREAD

**Issue by commi235** [mt-ag/apex-flowsforapex#42]
flow_subflows needs to always be joined to flow_processes and afterwards joined to flow_objects using bpmn_id and dgrm_id

**Comment by rallen2010** [comment]
One problem is that objt_id is not persistent across diagram parsing / re-parsing, whereas bpmn_id is.  Switching everything to use objt_id means that you couldn't change a process that is currently running, and also affects definition of user tasks, sendTasks, etc while we don't have them defined in the BPMN.

**Comment by commi235** [comment]
This is taken care of by using the natural key for joining.
Always combination of dgrm_id + bpmn_id

**Comment by commi235** [comment]
@nielsdebr Did you check for this in the demo app?
