### ISSUE TITLE
Parse default connection

### ISSUE THREAD

**Issue by commi235** [mt-ag/apex-flowsforapex#46]
On Gateways parse the attribute for default connection.  
Enhance connections table with flag for default.

**Comment by rallen2010** [comment]
can we define column for this, please?

How about flow_connections - add column conn_default_path varchar2(1) null - values in 'Y', 'N' to flow_connections for this?

**Comment by rallen2010** [comment]
From Moritz, for the record...

ALTER TABLE flow_connections ADD (
    conn_is_default NUMBER DEFAULT 0 NOT NULL
);
ALTER TABLE flow_connections
    ADD CHECK ( conn_is_default IN ( 0, 1 ) );

**Comment by rallen2010** [comment]
flow_engine support for this implemented.

**Comment by commi235** [comment]
Datamodel and parser support implemented
