### ISSUE TITLE
Remove OBJT_TYPE from Parser and then from database

### ISSUE THREAD

**Issue by rallen2010** [mt-ag/apex-flowsforapex#47]
flow_objects.objt_type was created to contain 'PROCESS' or 'SUBPROCESS' when the BPMN is parsed in V3 to allow 1 level of sub processes..

For V4, we allowed an arbitrary depth of sub-process nesting, and stopped using flow_objects.objt_type in the engine.

In V5.0, I have (already) removed all references to flow_objects.objt_type in flow_engine.  So please could we remove references to this in flow_parser, and once that is complete, remove the column from flow_objects.

**Comment by commi235** [comment]
Same is true for flow_connections.conn_type column.  
Removing that also.

**Comment by commi235** [comment]
feature branches merged.
