### ISSUE TITLE
Auditing & Logging

### ISSUE THREAD

**Issue by rallen2010** [mt-ag/apex-flowsforapex#9]
Many business implementations of this package are going to want to record details of process instance and their associated subflows and steps to track who has performed these tasks, when, status, etc. 

The approach so far is to keep this information out of the run time, operational tables in order to maintain performance and to stop long term accumulation of audit trail data in with the run time operational data.

The requirement to track visited notes in the diagram viewer means that we have added basic runtime logging as a process steps through a diagram.  These are currently cleaned up (i.e., deleted) when a process is reset or deleted.  

We should add a small sub-system to capture these log records, enhance, and move into longer term audit trail.

For bonus marks, we could add some basic analytics on these tables showing, for example,
- frequency & recency of process (diagram) runs
- end to end process run times (min, max, typical)
- step wait times
- step failure frequency, etc.
fairly simple stand alone sub-project for somebody who wants to get involved, once the core is designed.

If we don't do it, I think many projects will keep building & re-building this.

We should look at requirements in this for error messages / status, logging & debug for tasks, inc scripttasks and service tasks.  When these are run from a timer, they run outside of an APEX session, and so APEX debug, etc. aren't available.

**Comment by rallen2010** [comment]
remaining tasks after 12 Aug Merge:

- [ ] Subflow / task Events: Ensure became_current time is being correctly set
- [ ] Subflow / task events: Add comment & log current / started but non-completed activities in reset / terminate / interupting boundary events ?
- [ ] Variable Events:  Log
- [ ] Variable Events: test
- [ ] Anonymous Event Option for privacy tied to config parameter
- [ ] Flow Events: Implement
- [ ] Flow Events: Test
- [ ] Documentation
- [ ] add to Tutorial
- [ ] add config parameters to instal / upgrade scripts

**Comment by LouisMoreaux** [comment]
Delivered in version 21.1
