### ISSUE TITLE
Parallel Flows with no waiting Task do not use all paths

### ISSUE THREAD

**Issue by commi235** [mt-ag/apex-flowsforapex#93]
When there is a parallel gateway and on all paths there are no tasks the engine would wait on only the "first" path is processed.

[Diagram Example for Bug](https://github.com/mt-ag/apex-flowsforapex/files/5671126/and_bug.txt)

**Comment by rallen2010** [comment]
For the record, there Are 2 work arounds which will prevent this problem, in advance of a fix.  

First is to add one task that stops onto the first parallel section. 

Second is to serialise the tasks in the parallel sections - they are both operating inside of a single transaction, and so specifying that they operate in parallel doesn't really achieve any parallelism.

**Comment by commi235** [comment]
Agreed, still a bug and let me try to get it fixed for 5.0.1

**Comment by commi235** [comment]
Moved to 5.1.0 as it will require some engine rework.

**Comment by rallen2010** [comment]
![parallelRace](https://user-images.githubusercontent.com/6522588/105367262-2ecaed00-5bf8-11eb-8678-eff30fb5325f.png)
Test Case now works.  Also tested with inclusive gateways in place of the parallel ones.
