### ISSUE TITLE
A Question about administration of Flows

### ISSUE THREAD

**Issue by JacoFourie** [mt-ag/apex-flowsforapex#98]
Hi. I have a question about the administration of flows. I installed the Apex module and played around with it. It looks amazing and is almost 100% what I am looking for. We have been using Oracle Workflow for 20 years. The front end is Oracle Forms and the backend is Oracle Workflow. Oracle Workflow was deprecated standalone in 2003 but as it is PL/SQL based it still works fine. We are busy migrating the Forms front end from Forms to Apex and still used the Workflow backend. In the monitor module of Workflow you are able to view the process the same way as you can. But you are also able to expedite the flow from a certain point again. Let's say you have a very long-running process, at some point, it has to take a certain path and follow a transition based on some data, for whatever reason the data was wrong at that point and the process took the wrong path, we are able to fix the data and then let the process execute from a point that we select again. I do not see that function in Flows. Do you have to reset the full process? Some of our processes run for days and we won't be able to reset the full process.

**Comment by JacoFourie** [comment]
Here is a sample I am talking about. As you can see in this flow the process is waiting for approval 

![image](https://user-images.githubusercontent.com/17771641/102909298-6facd600-4481-11eb-9a71-b7d349b15a20.png)

In the monitor I can go to any node and direct the flow in a new direction. Let say that the person was a level 10. I can go to the Get reporting level node and force the flow down the level 10 path. Only admins have this power not normal users. 

![image](https://user-images.githubusercontent.com/17771641/102909512-bef30680-4481-11eb-8bfd-6f593ba19c30.png)

**Comment by rallen2010** [comment]
HI.  I noticed your great comments on YouTube earlier today!
Interesting problem.  I'm thinking that a solution might be to use the process error or escalation mechanisms in BPMN.  If the process doesn't complete a step correctly, you raised an error or an escalation, which starts a process flow that notifies you & allows you to fix the data before continuing???  I think it's more of a problem if the flow has a technical error (vs. process error).  might that work?

**Comment by JacoFourie** [comment]
We are at a point now where we have to replace Workflow as the monitor is written in Java and the browsers no longer support it, Only IE still supports Java so we have to keep IE around for our admins to be able to view the monitor. I guess if we understand the data structure of Flows we should be able to write an update statement to force the flow in a certain direction again, but it would be great if you can do it in die GUI front end.

**Comment by rallen2010** [comment]
On your specific example, if something gets stuck at a gateway, I guess you could go into the Flow Monitor & manually set the process variable that contains the gateway routing info & force it go down a different path.  I haven't tried, but should work if its stuck at the gateway.

**Comment by JacoFourie** [comment]
That can work if you get stuck or you have an error, but we all know that data sometimes get out of sync between systems, What if the data is fine and is valid at the point of execution but is wrong type because of a timing issue, Like the level example above. It takes 2 different paths based on what the level is at the point of execution, If the level is 10 it takes one path and another for any other level, Lets make up a logic error. The HR system has the level and had a problem during a batch job and failed to update the level to 10. When the person starts the process it will follow the path for non-level 10s. The person will log a call to ask why is the process following that path, The admin will investigate and see that the level was wrong at the time of execution, fix the level, and force the process from the same point it went wrong.

**Comment by JacoFourie** [comment]
You have done amazing work to get it to this point, I have been playing with other opensource BPMN engines also. I managed to get Activity working also with Apex, but it also has the issue of the administration if something goes wrong and a wrong path is taken how do you get it back on the correct path after fixing the issue.

**Comment by rallen2010** [comment]
We haven't done anything so far to handle making models go backwards or 'putting trains back on different rails' etc.  With all of the parallel tracks and boundary event handlers and things in BPMN, it's hard to know what you could or should allow, if you were to do things like this -- once the model gets running with parallel sections and etc., the effects of some of those things are hard to quantify.  There are additional BPMN constructs that we haven't got to yet, for "transactions" and compensation events, etc that might help unwind you back to a manual intervention point.  But we haven't got there yet.  We currently only have fairly rudimentary management / monitoring tools (with. the Flows for APEX app that ships with product).  But as we start to get some production users -- which appears to be happening quite quickly! - I can see that a development task will be better management.  We're already working on model /diagram versioning support, that will make processes more manageable.

**Comment by nielsdebr** [comment]
Thanks for mentioning this and great to see you evaluating Flows for APEX!

Yes, it is something we should cover for admins in the front-end in a future release.

**Comment by JacoFourie** [comment]
@nielsdebr that is good news. It will give the engine so much power. I personally think Oracle won't be happy with you as this is competing with their BPMN Suite, but don't let that stop you.

I have one more quick question. when you start a process. Can you start it synchronous or asynchronous? Let's say your first PL/SQL task in a process needs to update 10million records that will take 5 minutes. You want to start that process async so that the control returns to the user immediately, if you start it synch the user will have to wait 5 minutes before the Apex page is active again. 

Again I am very impressed with what you have at this point. I have more than 20 years of process automation experience and this is very cool to see. I am building a system for a small nonprofit and I will be using Flows for them.

**Comment by rallen2010** [comment]
My original design idea was that you should be able to start tasks synchronously or asynchronously - for exactly the reasons you mention.  So far, we've done the easy one to get us going and to prove the concept of script tasks, etc.  We need a volunteer to build the asynchronous server for us. If we enqueue the job as part of the workflow transaction, we need a process that works through what ever is on the queue...

**Comment by JacoFourie** [comment]
This should not be too hard to do. If you want to start a process async just send it to a server process via message queues, You can use Advanced Queueing or even DBMS_PIPES so that the process is started on its own thread and then return to the user once the call is made.

**Comment by nielsdebr** [comment]
We will adopt AQ for this in a future release, not only for this requirement, so stay tuned. :)
